Error	eapol-authentication-failed	802.1X/EAPOL is enabled on one or more LAN interfaces, but authentication failed...
Error	hotspot-login-proc-not-defined	The browserLoginProc or browserLogoutProc testvar specified the name of a TCL pr...
Error	invalid-ipsec-tunnel-configuration	CDRouter encountered an error while trying to load one of the IPsec tunnel confi...
Error	no-ftp-user-with-permission-type	Some CDRouter Storage tests require an FTP user with a specific permission::ftpu...
Error	no-lan-dhcp-address	CDRouter attempted to acquire a DHCP lease on one of its LAN interfaces during t...
Error	no-lan-dhcpv6-ia-na-binding	CDRouter attempted to establish a DHCPv6 IA_NA binding on one of its LAN interfa...
Error	no-lan-pppoe-address	CDRouter attempted to establish a PPPoE link on its primary LAN interface during...
Error	no-smb-user-with-permission-type	Some CDRouter Storage tests require an SMB user with a specific permission::smbu...
Error	no-smb-user-with-permission-type-ipv4	Some CDRouter Storage tests require an SMB user with an IPv4 server::smbuser add...
Error	no-wan-autoconf-address	When ipv6WanMode is set to 'autoconf' or ipv6WanMode is 'PPPoE' and ipv6PPPoEAdd...
Error	no-wan-dhcp-address	CDRouter attempted to assign a DHCP address on one of its WAN interfaces during ...
Error	no-wan-dhcpv6-address	CDRouter expected the device to request a DHCPv6 IA_NA binding on one of its WAN...
Error	no-wan-ppp-link	CDRouter attempted to establish an L2TP/PPTP link on one of its WAN interfaces d...
Error	no-wan-pppoe-dhcpv6-address	CDRouter expected the device to request a DHCPv6 IA_NA binding over the IPv6 PPP...
Error	no-wan-pppoe-ipv6-link	CDRouter attempted to establish an IPv6 PPPoE link on one of its WAN interfaces ...
Error	no-wan-pppoe-link	CDRouter attempted to establish a PPPoE link on one of its WAN interfaces during...
Error	no-wan-tr069-inform	The acsIp testvar is uncommented in your configuration file which enables the in...
Error	no-wan-tr069-xmpp-connection-request	The acsIp testvar is uncommented in your configuration file which enables the in...
Error	unable-to-associate-authenticate-to-ssid	One or more of CDRouter's LAN interfaces are wireless. When wireless is used CD...
Error	unable-to-locate-hat	CDRouter could not locate the HomeKit Accessory Tester. This is needed to run an...
Error	unable-to-locate-ssid	One or more of CDRouter's LAN interfaces are wireless. When wireless is used CD...
Error	unable-to-renew-dhcp-lease	Before running each testcase, CDRouter Multiport ensures each additional LAN int...
Error	unable-to-start-suricata	CDRouter was unable to bring up Suricata during start. Please see the start log...