# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditdut():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editdut(self):
    # Test name: edit dut
    # Step # | name | target | value
    # 1 | open | /admin/unums | 
    self.driver.get("https://my.minim.co/admin/unums")
    # 2 | setWindowSize | 1178x691 | 
    self.driver.set_window_size(1178, 691)
    # 3 | click | id=q_fuzzy_search | 
    self.driver.find_element(By.ID, "q_fuzzy_search").click()
    # 4 | type | id=q_fuzzy_search | b1:ef
    self.driver.find_element(By.ID, "q_fuzzy_search").send_keys("b1:ef")
    # 5 | click | name=commit | 
    self.driver.find_element(By.NAME, "commit").click()
    # 6 | click | css=#unum_1782120 > .col-lan_mac_address | 
    self.driver.find_element(By.CSS_SELECTOR, "#unum_1782120 > .col-lan_mac_address").click()
    # 7 | click | linkText=Edit | 
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
  
